[package]
name = "xor-redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis-module = "*"

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_arch = "aarch64")'.dependencies]
